# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 3a07b347a2a23574bb1e9d230326e61d586b5185e43cc9c6ac4c9bd9f7a8a4c241045eb5d21c3ff81e28501e5de33d638f4777a7bb6834effebbd811ea540442

test:
  secret_key_base: 4eb4355ac54034056bc72cdbe900f498061b86534f230e98da3564fb478aa2ef664327000353321e1d18b63b5580882372f254ab22afa9638f68c2cd128d8ac0

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
